"""0001 baseline

Revision ID: b1bec9f73123
Revises: 
Create Date: 2026-09-28 20:46:08.805992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001_baseline'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('centros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_certificados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=20), nullable=False),
    sa.Column('tabla', sa.String(length=50), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=False),
    sa.Column('datos_anteriores', sa.JSON(), nullable=True),
    sa.Column('datos_nuevos', sa.JSON(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('folios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rangoId', sa.Integer(), nullable=False),
    sa.Column('anioCert', sa.Integer(), nullable=False),
    sa.Column('tipoCert_id', sa.Integer(), nullable=False),
    sa.Column('folio', sa.Integer(), nullable=False),
    sa.Column('digitado', sa.Boolean(), nullable=True),
    sa.Column('escaneado', sa.Boolean(), nullable=True),
    sa.Column('nulo', sa.Boolean(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('createAt', sa.DateTime(), nullable=True),
    sa.Column('updateAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tipoCert_id'], ['tipo_certificados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('folios', schema=None) as batch_op:
        batch_op.create_index('idx_folio_anioCert', ['anioCert'], unique=False)
        batch_op.create_index('idx_folio_digitado', ['digitado'], unique=False)
        batch_op.create_index('idx_folio_escaneado', ['escaneado'], unique=False)
        batch_op.create_index('idx_folio_estado', ['estado'], unique=False)
        batch_op.create_index('idx_folio_nulo', ['nulo'], unique=False)
        batch_op.create_index('idx_folio_tipoCert_id', ['tipoCert_id'], unique=False)

    op.create_table('recepcion_folios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('anioCert', sa.Integer(), nullable=False),
    sa.Column('tipoCert_id', sa.Integer(), nullable=False),
    sa.Column('folioInicial', sa.Integer(), nullable=False),
    sa.Column('folioFinal', sa.Integer(), nullable=False),
    sa.Column('rangoId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tipoCert_id'], ['tipo_certificados.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rangoId')
    )
    with op.batch_alter_table('recepcion_folios', schema=None) as batch_op:
        batch_op.create_index('idx_recepcion_anioCert', ['anioCert'], unique=False)
        batch_op.create_index('idx_recepcion_tipoCert_id', ['tipoCert_id'], unique=False)

    op.create_table('devolucion_folios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folio_id', sa.Integer(), nullable=False),
    sa.Column('fechaDevolucion', sa.Date(), nullable=False),
    sa.Column('centroId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['centroId'], ['centros.id'], ),
    sa.ForeignKeyConstraint(['folio_id'], ['folios.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devolucion_folios', schema=None) as batch_op:
        batch_op.create_index('idx_devolucion_centroId', ['centroId'], unique=False)
        batch_op.create_index('idx_devolucion_folio_id', ['folio_id'], unique=False)
        batch_op.create_index('idx_devolucion_userId', ['userId'], unique=False)

    op.create_table('entrega_folios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folio_id', sa.Integer(), nullable=False),
    sa.Column('fechaEntrega', sa.Date(), nullable=False),
    sa.Column('centroId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['centroId'], ['centros.id'], ),
    sa.ForeignKeyConstraint(['folio_id'], ['folios.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entrega_folios', schema=None) as batch_op:
        batch_op.create_index('idx_entrega_centroId', ['centroId'], unique=False)
        batch_op.create_index('idx_entrega_folio_id', ['folio_id'], unique=False)
        batch_op.create_index('idx_entrega_userId', ['userId'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entrega_folios', schema=None) as batch_op:
        batch_op.drop_index('idx_entrega_userId')
        batch_op.drop_index('idx_entrega_folio_id')
        batch_op.drop_index('idx_entrega_centroId')

    op.drop_table('entrega_folios')
    with op.batch_alter_table('devolucion_folios', schema=None) as batch_op:
        batch_op.drop_index('idx_devolucion_userId')
        batch_op.drop_index('idx_devolucion_folio_id')
        batch_op.drop_index('idx_devolucion_centroId')

    op.drop_table('devolucion_folios')
    with op.batch_alter_table('recepcion_folios', schema=None) as batch_op:
        batch_op.drop_index('idx_recepcion_tipoCert_id')
        batch_op.drop_index('idx_recepcion_anioCert')

    op.drop_table('recepcion_folios')
    with op.batch_alter_table('folios', schema=None) as batch_op:
        batch_op.drop_index('idx_folio_tipoCert_id')
        batch_op.drop_index('idx_folio_nulo')
        batch_op.drop_index('idx_folio_estado')
        batch_op.drop_index('idx_folio_escaneado')
        batch_op.drop_index('idx_folio_digitado')
        batch_op.drop_index('idx_folio_anioCert')

    op.drop_table('folios')
    op.drop_table('audit_logs')
    op.drop_table('usuarios')
    op.drop_table('tipo_certificados')
    op.drop_table('centros')
    # ### end Alembic commands ###
