"""0002 integrity

Revision ID: a00c3335a79a
Revises: 0001_baseline
Create Date: 2026-09-28 20:47:52.232709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002_integrity'
down_revision = '0001_baseline'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devolucion_folios', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_devolucion_folios_folio_id', ['folio_id'])

    with op.batch_alter_table('entrega_folios', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_entrega_folios_folio_id', ['folio_id'])

    with op.batch_alter_table('folios', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_folios_anio_tipo_folio', ['anioCert', 'tipoCert_id', 'folio'])
        batch_op.create_unique_constraint('uq_folios_rangoId_folio', ['rangoId', 'folio'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folios', schema=None) as batch_op:
        batch_op.drop_constraint('uq_folios_rangoId_folio', type_='unique')
        batch_op.drop_constraint('uq_folios_anio_tipo_folio', type_='unique')

    with op.batch_alter_table('entrega_folios', schema=None) as batch_op:
        batch_op.drop_constraint('uq_entrega_folios_folio_id', type_='unique')

    with op.batch_alter_table('devolucion_folios', schema=None) as batch_op:
        batch_op.drop_constraint('uq_devolucion_folios_folio_id', type_='unique')

    # ### end Alembic commands ###
